# GApps dependencies
PRODUCT_COPY_FILES += \
    vendor/google/gapps/proprietary/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh:google \
    vendor/google/gapps/proprietary/system/app/PrebuiltBugle/lib/arm/libframesequence.so:system/app/PrebuiltBugle/lib/arm/libframesequence.so:google \
    vendor/google/gapps/proprietary/system/app/PrebuiltBugle/lib/arm/libgiftranscode.so:system/app/PrebuiltBugle/lib/arm/libgiftranscode.so:google \
    vendor/google/gapps/proprietary/system/app/Chrome/lib/arm/libchrome.so:system/app/Chrome/lib/arm/libchrome.so:google \
    vendor/google/gapps/proprietary/system/app/Chrome/lib/arm/libchromium_android_linker.so:system/app/Chrome/lib/arm/libchromium_android_linker.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libbitmap_parcel.so:system/app/Drive/lib/arm/libbitmap_parcel.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libdocscanner_image.so:system/app/Drive/lib/arm/libdocscanner_image.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libdocsimageutils.so:system/app/Drive/lib/arm/libdocsimageutils.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libfileutils.so:system/app/Drive/lib/arm/libfileutils.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libfoxit.so:system/app/Drive/lib/arm/libfoxit.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/librectifier.so:system/app/Drive/lib/arm/librectifier.so:google \
    vendor/google/gapps/proprietary/system/app/Drive/lib/arm/libwebp_android.so:system/app/Drive/lib/arm/libwebp_android.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsDocs/lib/arm/libdocsimageutils.so:system/app/EditorsDocs/lib/arm/libdocsimageutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsDocs/lib/arm/libfileutils.so:system/app/EditorsDocs/lib/arm/libfileutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsDocs/lib/arm/libkix_ndk1.so:system/app/EditorsDocs/lib/arm/libkix_ndk1.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsDocs/lib/arm/librawpixeldata_native.so:system/app/EditorsDocs/lib/arm/librawpixeldata_native.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsDocs/lib/arm/libwebp_android.so:system/app/EditorsDocs/lib/arm/libwebp_android.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSheets/lib/arm/libdocsimageutils.so:system/app/EditorsSheets/lib/arm/libdocsimageutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSheets/lib/arm/libfileutils.so:system/app/EditorsSheets/lib/arm/libfileutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSheets/lib/arm/librawpixeldata_native.so:system/app/EditorsSheets/lib/arm/librawpixeldata_native.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSheets/lib/arm/libritz_ndk1.so:system/app/EditorsSheets/lib/arm/libritz_ndk1.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSheets/lib/arm/libwebp_android.so:system/app/EditorsSheets/lib/arm/libwebp_android.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSlides/lib/arm/libdocsimageutils.so:system/app/EditorsSlides/lib/arm/libdocsimageutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSlides/lib/arm/libfileutils.so:system/app/EditorsSlides/lib/arm/libfileutils.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSlides/lib/arm/libpunch_ndk1.so:system/app/EditorsSlides/lib/arm/libpunch_ndk1.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSlides/lib/arm/librawpixeldata_native.so:system/app/EditorsSlides/lib/arm/librawpixeldata_native.so:google \
    vendor/google/gapps/proprietary/system/app/EditorsSlides/lib/arm/libwebp_android.so:system/app/EditorsSlides/lib/arm/libwebp_android.so:google \
    vendor/google/gapps/proprietary/system/app/LatinImeGoogle/lib/arm/libjni_keyboarddecoder.so:system/app/LatinImeGoogle/lib/arm/libjni_keyboarddecoder.so:google \
    vendor/google/gapps/proprietary/system/app/LatinImeGoogle/lib/arm/libjni_unbundled_latinimegoogle.so:system/app/LatinImeGoogle/lib/arm/libjni_unbundled_latinimegoogle.so:google \
    vendor/google/gapps/proprietary/system/app/GoogleTTS/lib/arm/libpatts_engine_jni_api_neon_ub.210305063.so:system/app/GoogleTTS/lib/arm/libpatts_engine_jni_api_neon_ub.210305063.so:google \
    vendor/google/gapps/proprietary/system/app/GoogleTTS/lib/arm/libpatts_engine_jni_api_ub.210305063.so:system/app/GoogleTTS/lib/arm/libpatts_engine_jni_api_ub.210305063.so:google \
    vendor/google/gapps/proprietary/system/app/GoogleTTS/lib/arm/libspeexwrapper_ub.210305063.so:system/app/GoogleTTS/lib/arm/libspeexwrapper_ub.210305063.so:google \
    vendor/google/gapps/proprietary/system/app/Maps/lib/arm/libcrashreporterer.so:system/app/Maps/lib/arm/libcrashreporterer.so:google \
    vendor/google/gapps/proprietary/system/app/Maps/lib/arm/libgmm-jni.so:system/app/Maps/lib/arm/libgmm-jni.so:google \
    vendor/google/gapps/proprietary/system/app/WebViewGoogle/lib/arm/libwebviewchromium.so:system/app/WebViewGoogle/lib/arm/libwebviewchromium.so:google \
    vendor/google/gapps/proprietary/system/etc/g.prop:system/etc/g.prop:google \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml:google \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml:google \
    vendor/google/gapps/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml:google \
    vendor/google/gapps/proprietary/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml:google \
    vendor/google/gapps/proprietary/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar:google \
    vendor/google/gapps/proprietary/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar:google \
    vendor/google/gapps/proprietary/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar:google \
    vendor/google/gapps/proprietary/system/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so:google \
    vendor/google/gapps/proprietary/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so:google \
    vendor/google/gapps/proprietary/system/priv-app/GoogleDialer/lib/arm/libvariablespeed.so:system/priv-app/GoogleDialer/lib/arm/libvariablespeed.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libAppDataSearch.so:system/priv-app/PrebuiltGmsCore/lib/arm/libAppDataSearch.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libNearbyApp.so:system/priv-app/PrebuiltGmsCore/lib/arm/libNearbyApp.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libWhisper.so:system/priv-app/PrebuiltGmsCore/lib/arm/libWhisper.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libconscrypt_gmscore_jni.so:system/priv-app/PrebuiltGmsCore/lib/arm/libconscrypt_gmscore_jni.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libdirect-audio.so:system/priv-app/PrebuiltGmsCore/lib/arm/libdirect-audio.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libgcastv2_base.so:system/priv-app/PrebuiltGmsCore/lib/arm/libgcastv2_base.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libgcastv2_support.so:system/priv-app/PrebuiltGmsCore/lib/arm/libgcastv2_support.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libgms-ocrclient.so:system/priv-app/PrebuiltGmsCore/lib/arm/libgms-ocrclient.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libgmscore.so:system/priv-app/PrebuiltGmsCore/lib/arm/libgmscore.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libjgcastservice.so:system/priv-app/PrebuiltGmsCore/lib/arm/libjgcastservice.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libleveldbjni.so:system/priv-app/PrebuiltGmsCore/lib/arm/libleveldbjni.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libsslwrapper_jni.so:system/priv-app/PrebuiltGmsCore/lib/arm/libsslwrapper_jni.so:google \
    vendor/google/gapps/proprietary/system/priv-app/PrebuiltGmsCore/lib/arm/libwearable-selector.so:system/priv-app/PrebuiltGmsCore/lib/arm/libwearable-selector.so:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm:google \
    vendor/google/gapps/proprietary/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist:google \
    vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/head-y0-yi45-p0-pi45-rn30-ri30.4a-v24-tree7-2-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/head-y0-yi45-p0-pi45-rp30-ri30.4a-v24-tree7-2-wmd.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/pose-r.8.1.bin:google \
	vendor/google/gapps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/pose-y-r.8.1.bin:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libgcam.so:system/app/GoogleCamera/lib/arm/libgcam.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libgcam_swig_jni.so:system/app/GoogleCamera/lib/arm/libgcam_swig_jni.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libjni_jpegutil.so:system/app/GoogleCamera/lib/arm/libjni_jpegutil.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libjni_tinyplanet.so:system/app/GoogleCamera/lib/arm/libjni_tinyplanet.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libjpeg.so:system/app/GoogleCamera/lib/arm/libjpeg.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/liblightcycle.so:system/app/GoogleCamera/lib/arm/liblightcycle.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libnativehelper_compat_libc++.so:system/app/GoogleCamera/lib/arm/libnativehelper_compat_libc++.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/librefocus.so:system/app/GoogleCamera/lib/arm/librefocus.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/librs.layered_filter_fast_f32.so:system/app/GoogleCamera/lib/arm/librs.layered_filter_fast_f32.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/librsjni.so:system/app/GoogleCamera/lib/arm/librsjni.so:google \
    vendor/google/gapps/proprietary/optional/camera/hammerhead/app/GoogleCamera/lib/arm/libRSSupport.so:system/app/GoogleCamera/lib/arm/libRSSupport.so:google \

PRODUCT_PACKAGES += \
    AndroidForWork \
    Books \
    CalendarGooglePrebuilt \
    CalendarProvider \
	Chrome \
    ChromeBookmarksSyncAdapter \
    CloudPrint2.apk \
    ConfigUpdater \
    Drive \
    EditorsDocs \
    EditorsSheets \
    EditorsSlides \
    GalleryGoogle \
    GenieWidget \
    GCS \
    PrebuiltBugle \
    PrebuiltExchange3Google \
    PrebuiltGmail \
    GoogleBackupTransport \
    GoogleCamera \
    GoogleContacts \
    GoogleContactsSyncAdapter \
    GoogleDialer \
    GoogleEars \
    GoogleEarth \
    GoogleFeedback \
    GoogleHome \
    GoogleLoginService \
    GooglePartnerSetup \
    GoogleServicesFramework \
    GoogleTTS \
    Hangouts \
    Keep \
    LatinImeGoogle \
    Magazines \
    Maps \
    MediaShortcuts \
    MediaUploader \
    Music2 \
    OneTimeInitializer \
    Phonesky \
    PlayGames \
    PlusOne \
    PrebuiltGmsCore \
    QuickOffice \
    SetupWizard \
    Street \
    TagGoogle \
    talkback \
    TimeService \
    Velvet \
    Videos \
    Wallet \
    YouTube \

